export const addFundInitalPayload = {
  managementFeeA: 0,
  managementFeeB: 0,
  // managementFeeC: 0,
  performanceFeeA: 0,
  performanceFeeB: 0,
  // performanceFeeC: 0,
  complianceFee: 0,
  trusteesFee: 0,
  unitStartingPrice: null,
  pricingInputs: null,
  currency: "Rand (R)",
  auditFee: 0,
  fundRiskRating: null,
  isVatapplicable: null,
  vat: null,
  fundName: null,
  fundPhilosophy: null,
  inceptionDate: null,
  fundDynamicField: [],
};

export const addFundInitalPayloadErrors = {
  managementFeeA: "Please enter valid management fee A",
  managementFeeB: "Please enter valid management fee B",
  // managementFeeC: "Please enter management fee C",
  performanceFeeA: "Please enter valid performance fee A",
  performanceFeeB: "Please enter valid performance fee B",
  // performanceFeeC: "Please enter performance fee C",
  complianceFee: "Please enter valid compliance fee",
  trusteesFee: "Please enter valid trustees fee",
  unitStartingPrice: "Please enter valid unit starting price",
  pricingInputs: "Please enter pricing inputs",
  currency: "Please select currency",
  auditFee: "Please enter valid audit fee",
  fundRiskRating: "Please select fund rating",
  isVatapplicable: "Please select vat applicable",
  vat: "Please enter vat ",
  fundName: "Please enter fund name",
  fundPhilosophy: "Please enter fund philosophy",
  inceptionDate: "Please select inception date",
};
