# The on key is used to define when
name: BuildCI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Runner meaningful name
      - name: Checkout
        # Ready-to-use action made by GH or third party
        # companies
        # We can recognize the GH actions from the third party
        # ones checking the name prefix.
        # `actions/` = GH
        # `something-else/` = third party
        uses: actions/checkout@v2

      - name: Setup React Ts
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12

      - name: Install server dependencies
        run: npm install

      - name: Generate build
        run: npm run build

      - uses: bahmutov/npm-install@HEAD

      - run: npm ci

      # - name: Run ESLint
      # Run the lint custom NPM command that triggers the
      # ESLint linter check
      # run: npm run lint

      # - name: Run Prettier
      #   # Run the format:check custom NPM command
      #   # that runs prettier to check code is formated
      #   uses: creyD/prettier_action@v4.2
      #   with:
      #     # This part is also where you can pass other options, for example:
      #     prettier_options: --write **/*.{js,md}
      #     only_changed: True

      - uses: actions/checkout@v1

      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v1
        with:
          name: react-github-actions-build
          path: build
